import Head from 'next/head';

import BannerTop from "@components/Header/BannerTop";
import Youtube from "@components/Header/Youtube";



 const HomePage = () => {
  return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <BannerTop/>
      </>

  )
}

export default HomePage;