import Head from 'next/head'
import Image from 'next/image'
import Welcome from "../src/components/Header";
import styles from '../src/assets/css/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Welcome/>
      </main>

      <footer className={styles.footer}>
        Footer của tôi
      </footer>
    </div>
  )
}
